name: flutter_doctor
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wnpmish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  provider: ^4.3.2+2
  font_awesome_flutter: ^8.10.0
  curved_navigation_bar: ^0.3.4
  geolocator: ^5.3.1
  animated_widgets: ^1.0.6
  flutter_svg:
  flutter_facebook_login: ^1.2.0
  google_sign_in: ^4.5.6
  dio: ^3.0.10
  fluttertoast: ^7.1.4
  form_field_validator: ^1.0.1
  wc_form_validators: ^0.1.1
  email_validator: ^1.0.6
  sqflite: ^1.3.0
  shared_preferences: ^0.5.12+4
  flutter_email_sender: ^4.0.0
  pin_entry_text_field: ^0.1.4
  mailer: ^3.2.1
  flutter_mailer: ^1.0.1
  flutter_gifimage: ^1.0.0
  flutter_spinkit: ^4.1.2+1
  webview_flutter: 
  camera:
  path_provider:
  path:
  image_picker: ^0.6.6+5
  tflite: ^1.1.1
  select_dialog: ^1.2.3
  keyboard_attachable: ^1.0.3
  page_transition:
  pie_chart:
  fl_chart: 
  #youtube_player_flutter: ^8.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/Components/
    - assets/images/home/
    - assets/images/home/orange0.jpg
    - assets/images/home/orange1.jpg
    - assets/images/home/orange2.jpg
    - assets/images/home/orange3.jpg
    - assets/images/home/corn.png
    - assets/images/home/Papaya.png
    - assets/images/farmer-avatar.svg
    - assets/images/rank3.png
    - assets/images/rating.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Logo
      fonts:
        - asset: assets/fonts/Logo.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Painter
      fonts:
        - asset: assets/fonts/Painter.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
